### ISSUE TITLE
(Error) Line 101: expect: command not found

### ISSUE THREAD

**Issue by pranavbhasin96** [flyingcharge/AutoVPN#4]
While running the script on fedora, it says line 101: expect: command not found.
I dont know what does "expect <<- Done" does, so please look into it.

**Comment by bakszero** [comment]
Which version of Fedora are you using?

**Comment by pranavbhasin96** [comment]
Fedora 23

**Comment by bakszero** [comment]
'expect' is not installed on your system. 
Install on Fedora using 'dnf install -y expect'.
Should work after that.
