### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by imsridhar** [flyingcharge/AutoVPN#8]
OUTPUT:
spawn openvpn --config linux_client.conf
Tue Jul  7 12:42:42 2020 WARNING: cannot stat file &apos;all.iiit.ac.in.key&apos;: No such file or directory (errno=2)
Options error: --key fails with &apos;all.iiit.ac.in.key&apos;: No such file or directory (errno=2)
Options error: Please correct these errors.

**Comment by bakszero** [comment]
It'd be great if you could specify the machine configuration on which you get the error.

A few questions:
1. Did you enter the correct user-email and password on prompt?
2. Can you verify if the file `/etc/openvpn/all.iiit.ac.in.key` exists on your system?

**Comment by imsridhar** [comment]
Sorry, it is working now. I had to re-install curl.
